-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brand_profiles
(
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    user_id bigint NOQT NULL,
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    industry character varying(255) COLLATE pg_catalog."default",
    logo_url character varying(255) COLLATE pg_catalog."default",
    website_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT brand_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT brand_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.campaigns
(
    end_date date,
    start_date date,
    brand_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    infl_id bigint,
    updated_at timestamp(6) with time zone,
    brief character varying(2000) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    influencer_id bigint NOT NULL,
    CONSTRAINT campaigns_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.collaboration_requests
(
    created_at timestamp(6) with time zone NOT NULL,
    from_user_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    to_user_id bigint,
    updated_at timestamp(6) with time zone,
    message character varying(1000) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT collaboration_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.contracts
(
    campaign_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    signed_brand_at timestamp(6) with time zone,
    signed_infl_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    terms_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT contracts_pkey PRIMARY KEY (id),
    CONSTRAINT contracts_campaign_id_key UNIQUE (campaign_id)
);

CREATE TABLE IF NOT EXISTS public.dialog_participants
(
    dialog_id bigint NOT NULL,
    participant_id bigint
);

CREATE TABLE IF NOT EXISTS public.dialogs
(
    campaign_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    CONSTRAINT dialogs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.influencer_profiles
(
    created_at timestamp(6) with time zone NOT NULL,
    followers_count bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    bio character varying(255) COLLATE pg_catalog."default",
    category character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    display_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT influencer_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT influencer_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.influencer_social_links
(
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    infl_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    platform character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT influencer_social_links_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.media_assets
(
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    infl_id bigint NOT NULL,
    size_bytes bigint,
    updated_at timestamp(6) with time zone,
    uploaded_at timestamp(6) with time zone,
    description character varying(255) COLLATE pg_catalog."default",
    media_type character varying(255) COLLATE pg_catalog."default",
    metadata jsonb,
    title character varying(255) COLLATE pg_catalog."default",
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT media_assets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.media_files
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    content oid NOT NULL,
    content_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default",
    duration integer,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    height integer,
    size bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    uploaded_by bigint NOT NULL,
    width integer,
    CONSTRAINT media_files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    asset_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    dialog_id bigint NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    read_at timestamp(6) with time zone,
    sender_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    body character varying(255) COLLATE pg_catalog."default",
    content character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    read_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    user_id bigint,
    payload jsonb,
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    score integer NOT NULL,
    campaign_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    target_id bigint,
    updated_at timestamp(6) with time zone,
    writer_id bigint,
    comment character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT ratings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schedule_items
(
    due_date date,
    campaign_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    done_at timestamp(6) with time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT schedule_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    refresh_token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    updated_at timestamp(6) with time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.verification_tokens
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT verification_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT uk6q9nsb665s9f8qajm3j07kd1e UNIQUE (token),
    CONSTRAINT ukdqp95ggn6gvm865km5muba2o5 UNIQUE (user_id)
);

ALTER TABLE IF EXISTS public.brand_profiles
    ADD CONSTRAINT fksj9au0kfjkqbmlqja9q47nilo FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS brand_profiles_user_id_key
    ON public.brand_profiles(user_id);


ALTER TABLE IF EXISTS public.campaigns
    ADD CONSTRAINT fk11wccd9snl7g5vmgq2exby2bl FOREIGN KEY (infl_id)
    REFERENCES public.influencer_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.campaigns
    ADD CONSTRAINT fkfq50y0el7o0nfi2ixuh40hp5b FOREIGN KEY (brand_id)
    REFERENCES public.brand_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.collaboration_requests
    ADD CONSTRAINT fk6m9l1www5himum4uqjmcsgnuo FOREIGN KEY (to_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.collaboration_requests
    ADD CONSTRAINT fkhnag154bcnbkekbkcs049awwi FOREIGN KEY (from_user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.contracts
    ADD CONSTRAINT fknk1bvi5t0iqfhy6pr5khjssrb FOREIGN KEY (campaign_id)
    REFERENCES public.campaigns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS contracts_campaign_id_key
    ON public.contracts(campaign_id);


ALTER TABLE IF EXISTS public.dialog_participants
    ADD CONSTRAINT fkewktqtk2mxvw9m1i8uosk78gk FOREIGN KEY (dialog_id)
    REFERENCES public.dialogs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.dialogs
    ADD CONSTRAINT fkemb88w1eno40mspj16u56jii2 FOREIGN KEY (campaign_id)
    REFERENCES public.campaigns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.influencer_profiles
    ADD CONSTRAINT fkap2ey8yowip926r5opnfre1n0 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS influencer_profiles_user_id_key
    ON public.influencer_profiles(user_id);


ALTER TABLE IF EXISTS public.influencer_social_links
    ADD CONSTRAINT fkdrlhbn36ge6okcamip8gvwy64 FOREIGN KEY (infl_id)
    REFERENCES public.influencer_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.media_assets
    ADD CONSTRAINT fksgjlvok6a29jxxn97uqjgbo7q FOREIGN KEY (infl_id)
    REFERENCES public.influencer_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fkdkkx1ykyeseajwofi8r9ep3ep FOREIGN KEY (asset_id)
    REFERENCES public.media_assets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fkjbkac2909pydsesgme6wc0mn5 FOREIGN KEY (dialog_id)
    REFERENCES public.dialogs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk50353wm7jjyibicvqfmwksp8w FOREIGN KEY (target_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fkfr9p7xtxobgeaat0bbc3h7xhg FOREIGN KEY (writer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fkjee6t3ev95ppw4jej2j7g2ydx FOREIGN KEY (campaign_id)
    REFERENCES public.campaigns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.schedule_items
    ADD CONSTRAINT fkemflh76nm1lmln1l3lyc5dl5e FOREIGN KEY (campaign_id)
    REFERENCES public.campaigns (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_sessions
    ADD CONSTRAINT fk8klxsgb8dcjjklmqebqp1twd5 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.verification_tokens
    ADD CONSTRAINT fk54y8mqsnq1rtyf581sfmrbp4f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukdqp95ggn6gvm865km5muba2o5
    ON public.verification_tokens(user_id);

END;