#############################
# default = local
#############################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/influ_match
    username: postgres
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E63...
      expiration: 86400000
      refresh-token:
        expiration: 604800000

---

#############################
# prod (Render / Azure App Service)
#############################
spring:
  config:
    activate:
      on-profile: prod  # <-- solo se activa si SPRING_PROFILES_ACTIVE=prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update  # opcional, puedes cambiar a `validate` en producción

  flyway:
    enabled: true       # también aplicable en prod si tienes migraciones

server:
  port: 80              # Render expone por defecto el puerto 80

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
