#############################
# default = local
#############################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/influ_match
    username: postgres
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 404E63...
      expiration: 86400000
      refresh-token:
        expiration: 604800000

---

#############################
# prod (Azure App Service)
#############################
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

server:
  port: ${PORT:8080}      # PORT si existe, fallback 8080

application:
  security:
    jwt:
      secret-key: ${APPLICATION_SECURITY_JWT_SECRET_KEY}
