--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-05-29 00:00:25

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16716)
-- Name: brand_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.brand_profiles (
    id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    description character varying(255),
    industry character varying(255),
    logo_url character varying(255),
    updated_at timestamp(6) with time zone,
    website_url character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.brand_profiles OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16715)
-- Name: brand_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.brand_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.brand_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16796)
-- Name: campaigns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaigns (
    id bigint NOT NULL,
    brief character varying(255),
    created_at timestamp(6) with time zone,
    end_date date,
    start_date date,
    status character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    brand_id bigint,
    infl_id bigint,
    CONSTRAINT campaigns_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ACTIVE'::character varying, 'FINISHED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.campaigns OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16795)
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16805)
-- Name: collaboration_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collaboration_requests (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    message character varying(255),
    status character varying(255),
    from_user_id bigint,
    to_user_id bigint,
    CONSTRAINT collaboration_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.collaboration_requests OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16804)
-- Name: collaboration_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collaboration_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collaboration_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16814)
-- Name: contracts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contracts (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    signed_brand_at timestamp(6) with time zone,
    signed_infl_at timestamp(6) with time zone,
    terms_url character varying(255),
    campaign_id bigint NOT NULL
);


ALTER TABLE public.contracts OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16813)
-- Name: contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16858)
-- Name: dialogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dialogs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    campaign_id bigint
);


ALTER TABLE public.dialogs OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16857)
-- Name: dialogs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dialogs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dialogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16724)
-- Name: influencer_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.influencer_profiles (
    id bigint NOT NULL,
    bio character varying(255),
    category character varying(255),
    country character varying(255),
    created_at timestamp(6) with time zone,
    display_name character varying(255) NOT NULL,
    followers_count bigint,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.influencer_profiles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16723)
-- Name: influencer_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.influencer_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.influencer_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16732)
-- Name: influencer_social_links; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.influencer_social_links (
    id bigint NOT NULL,
    platform character varying(255),
    url character varying(255) NOT NULL,
    infl_id bigint NOT NULL,
    CONSTRAINT influencer_social_links_platform_check CHECK (((platform)::text = ANY ((ARRAY['IG'::character varying, 'YT'::character varying, 'TT'::character varying, 'FB'::character varying, 'TW'::character varying, 'LN'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.influencer_social_links OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16731)
-- Name: influencer_social_links_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.influencer_social_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.influencer_social_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16741)
-- Name: media_assets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media_assets (
    id bigint NOT NULL,
    description character varying(255),
    media_type character varying(255),
    metadata jsonb,
    size_bytes bigint,
    title character varying(255),
    uploaded_at timestamp(6) with time zone,
    url character varying(255) NOT NULL,
    infl_id bigint NOT NULL,
    CONSTRAINT media_assets_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying, 'DOC'::character varying])::text[])))
);


ALTER TABLE public.media_assets OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16740)
-- Name: media_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16864)
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    body character varying(255),
    created_at timestamp(6) with time zone,
    read_at timestamp(6) with time zone,
    asset_id bigint,
    dialog_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16863)
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16890)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    payload jsonb,
    read_at timestamp(6) with time zone,
    type character varying(255),
    user_id bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['NEW_REQUEST'::character varying, 'MSG'::character varying, 'SCHEDULE'::character varying, 'RATING'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16889)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16899)
-- Name: ratings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ratings (
    id bigint NOT NULL,
    comment character varying(255),
    created_at timestamp(6) with time zone,
    score smallint NOT NULL,
    campaign_id bigint,
    target_id bigint,
    writer_id bigint
);


ALTER TABLE public.ratings OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16898)
-- Name: ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16820)
-- Name: schedule_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedule_items (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    done_at timestamp(6) with time zone,
    due_date date,
    title character varying(255) NOT NULL,
    campaign_id bigint
);


ALTER TABLE public.schedule_items OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16819)
-- Name: schedule_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedule_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16759)
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_sessions (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    refresh_token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_sessions OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16750)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255),
    status character varying(255),
    updated_at timestamp(6) with time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['INFLUENCER'::character varying, 'BRAND'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16749)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Completed on 2025-05-29 00:00:25

--
-- PostgreSQL database dump complete
--

