name: CI/CD to Azure App Service

on:
  push:
    branches: [ "main" ]      # dispara al hacer push a main
  workflow_dispatch:          # botón "Run workflow" en la UI (opcional)

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 🔑 da permiso de ejecución al wrapper
    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build JAR (skip tests)
      run: ./mvnw clean package -DskipTests        # genera el JAR

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: influmatch-api                   # nombre EXACTO de la Web App
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: target/InfluMatch_BackEnd-0.0.1-SNAPSHOT.jar
